version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=order
#      - MONGO_INITDB_ROOT_PASSWORD=order
#      - MONGO_INITDB_DATABASE=order-database
#      - MONGO_DB_USERNAME=order
#      - MONGO_DB_PASSWORD=order

volumes:
  mongodb_data:
    driver: local